name: Release Please

on:
  push:
    branches:
      - main

permissions:
  id-token: write

jobs:
  release-please:
    uses: voxpelli/ghatemplates/.github/workflows/release-please-bot.yml@main
    secrets: inherit
    with:
      app-id: '1082006'
